### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by JustinAiken** [danielbrodin/atom-project-manager#112]
This started popping up when I start Atom, after today's 1.15.9 update:

```
/Users/jaiken/.atom/packages/project-manager/lib/project-manager.coffee:134
TypeError: undefined is not a function
  at Object.module.exports.enableSettings (/Users/jaiken/.atom/packages/project-manager/lib/project-manager.coffee:134:17)
  at /Users/jaiken/.atom/packages/project-manager/lib/project-manager.coffee:103:12
  at parseContents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:105:7)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:186:24
  at FSReqWrap.oncomplete (fs.js:77:15)
```

This is just when I start up Atom - not doing any PM shortcuts or commands or such.

**Comment by danielbrodin** [comment]
The error should be gone now

**Comment by JustinAiken** [comment]
Does seem to be gone indeed, thanks for the quick fix! :)
