### ISSUE TITLE
Uncaught TypeError: Cannot read property 'paths' of undefined

### ISSUE THREAD

**Issue by norbornen** [danielbrodin/atom-project-manager#113]
**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v1.15.10

### Stack Trace

Uncaught TypeError: Cannot read property 'paths' of undefined

```
At /Users/*/.atom/packages/project-manager/lib/project-manager-view.coffee:67

TypeError: Cannot read property 'paths' of undefined
  at /Users/*/.atom/packages/project-manager/lib/project-manager-view.coffee:67:37
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:183:59
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

```

### Commands

```
  2x -0:02.2.0 project-manager:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "package-generator",
      "wrap-guide",
      "linter-coffeelint"
    ],
    "followSymlinks": true,
    "ignoredNames": [
      ".git",
      "Thumbs.db",
      ".TemporaryItems",
      "._.TemporaryItems",
      "._.apdisk",
      ".apdisk"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "project-manager": {
    "showPath": false,
    "sortBy": "group"
  }
}
```

### Installed Packages

```coffee
# User
coffee-navigator, v0.0.16
commands, v0.0.1
docblockr, v0.7.2
editor-stats, v0.17.0
file-icons, v1.5.7
file-type-icons, v0.6.0
highlight-line, v0.10.2
highlight-selected, v0.9.3
javascript-snippets, v1.0.0
jshint, v1.3.7
jsonlint, v1.1.2
language-jade, v0.4.0
language-mason, v2.0.4
language-pgsql, v0.2.0
linter, v0.12.6
linter-csslint, v0.0.13
linter-perl, v0.5.1
linter-xmllint, v0.0.6
monokai, v0.14.0
pretty-json, v0.3.3
project-manager, v1.15.10
remote-edit, v1.8.0

# Dev
No dev packages
```

**Comment by coopermaruyama** [comment]
I had this issue too, been happening for a while and haven't been able to use this useful package so I went ahead and patched it. I've opened a pull request at #115 however in the meantime until it's merged you can do the following:

```sh
apm develop project-manager
cd ~/github/project-manager
git remote add cooper git@github.com:coopermaruyama/atom-project-manager.git
git fetch cooper
git checkout patch-1
atom -d
``
