### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by qqquan** [danielbrodin/atom-project-manager#122]
Because my company blocks github access, and the proxy setup involves multiple IPs and user credentials, I have to install project-manger manually by
1. Download and extract master branch to a temp folder
2. Run command line in that folder: apm link
3. Click alt-shirt-p in windows

then I got the error.
It is an indispensable atom plugin to me. I would appreciate if you can fix the issue.

![pm_err](https://cloud.githubusercontent.com/assets/12763414/8776911/87fa2be8-2ec2-11e5-8719-a405b6bf8db3.PNG)

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v1.15.11

### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At module.js:330

Error: Cannot find module 'atom-space-pen-views'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\uidu7867\AppData\Local\atom\app-1.0.2\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (d:\myfiles_ibs\tools\atom\packages\atom-project-manager-master\lib\project-manager-view.coffee:1:33)
  at Object.<anonymous> (d:\myfiles_ibs\tools\atom\packages\atom-project-manager-master\lib\project-manager-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\uidu7867\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at atom-workspace.subscriptions.add.atom.commands.add.project-manager:toggle (d:\myfiles_ibs\tools\atom\packages\atom-project-manager-master\lib\project-manager.coffee:62:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\uidu7867\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\uidu7867\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\uidu7867\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\uidu7867\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\uidu7867\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:177:20)

```

### Commands

```
  2x -2:20.6.0 project-manager:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "obj",
      "src",
      "tstmp",
      ".bak"
    ]
  }
}
```

### Installed Packages

```coffee
# User
project-manager, v1.15.11

# Dev
No dev packages
```

**Comment by danielbrodin** [comment]
You still have to install all dependencies. Running apm install in the folder should solve it :)

**Comment by qqquan** [comment]
Thank you for the reply.

I got another error doing apm install:

d:\tools\atom\packages\atom-project-manager-master>apm install

gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.35 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.22.0/node-v0.22.0.tar.gz
gyp
d:\tools\atom\packages\atom-project-manager-master>

---------------------------------\\

I spent some time trying to figure out. I got my proxy configured and found the issue might be related to apm. The proxy setting seems be broken:

https://github.com/atom/apm/issues/322
