### ISSUE TITLE
Uncaught Error: Cannot find module './project-manager-view'

### ISSUE THREAD

**Issue by hd-deman** [danielbrodin/atom-project-manager#132]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.5
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.0.0

### Stack Trace

Uncaught Error: Cannot find module './project-manager-view'

```
At module.js:330

Error: Cannot find module './project-manager-view'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at atom-workspace.subscriptions.add.atom.commands.add.project-manager:toggle (/Users/deman/.atom/packages/project-manager/lib/project-manager.coffee:62:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -1:36.3.0 core:close (div.release-notes.padded.pane-item.native-key-bindings)
     -1:34.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:15.1.0 project-manager:toggle (atom-text-editor.editor.is-focused)
     -0:12.2.0 core:undo (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:09.1.0 project-manager:toggle (atom-text-editor.editor.is-focused)
     -0:08.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:08.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:03.7.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:02.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:02.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:02.1.0 project-manager:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ],
    "projectHome": "/Users/deman/projects"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-color-highlight, v3.0.9
atom-ctags, v4.2.0
autoclose-html, v0.18.0
autocomplete-paths, v1.0.2
docs-snippets, v0.8.0
file-icons, v1.6.9
file-types, v0.5.1
highlight-selected, v0.10.1
language-actionscript3, v0.3.0
language-apache, v1.3.0
language-bats, v0.1.0
language-chef, v0.5.0
language-docker, v1.1.3
language-hosts, v0.1.2
language-liquid, v0.4.0
language-nginx, v0.5.4
language-terraform, v0.5.0
language-vcl, v0.1.0
linter, v1.4.3
linter-bootlint, v0.0.6
linter-clang, v3.1.3
linter-clojure, v0.0.5
linter-coffeelint, v1.0.2
linter-cpplint, v0.1.4
linter-csslint, v1.0.5
linter-erb, v0.1.1
linter-eslint, v3.0.2
linter-flake8, v1.6.1
linter-flow, v0.1.6
linter-foodcritic, v0.4.0
linter-gjslint, v0.0.5
linter-hlint, v0.4.2
linter-htmlhint, v0.1.1
linter-javac, v1.1.0
linter-js-yaml, v1.1.1
linter-jscs, v2.0.4
linter-jshint, v1.1.5
linter-jsonlint, v0.1.4
linter-jsxhint, v0.1.2
linter-lua, v1.0.0
linter-pep257, v0.2.1
linter-pep8, v1.0.1
linter-php, v1.0.3
linter-phpcs, v1.0.6
linter-phpmd, v1.0.0
linter-puppet-lint, v0.4.0
linter-pylint, v1.0.0
linter-rubocop, v0.3.4
linter-ruby, v1.0.2
linter-scalac, v1.0.2
linter-scss-lint, v2.0.0
linter-shellcheck, v1.0.1
linter-tslint, v0.3.0
linter-xmllint, v0.0.7
minimap, v4.13.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.0
minimap-linter, v1.0.0
php-twig, v4.0.0
project-manager, v2.0.0
rspec-snippets, v0.4.0
serverspec-snippets, v0.1.0
ssh-config, v0.10.1
symbols-tree-view, v0.9.3
wakatime, v4.0.16
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by ymatuhin** [comment]
+

**Comment by esiao** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.5
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.0.0


### Stack Trace

Uncaught Error: Cannot find module './project-manager-view'

```
At module.js:330

Error: Cannot find module './project-manager-view'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at atom-workspace.subscriptions.add.atom.commands.add.project-manager:toggle (/Users/boldbeyond/.atom/packages/project-manager/lib/project-manager.coffee:59:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -3:07.2.0 core:copy (atom-text-editor.editor.is-focused)
  3x -3:06.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:05.1.0 core:paste (atom-text-editor.editor.is-focused)
     -3:01.8.0 core:cut (atom-text-editor.editor.is-focused)
  3x -2:59.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:55.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:55.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:54 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:53 core:paste (atom-text-editor.editor.is-focused)
  3x -2:50.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:39.8.0 core:save (atom-text-editor.editor.is-focused)
     -2:24.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:23.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:03.7.0 core:copy (atom-text-editor.editor.is-focused)
     -0:01.3.0 project-manager:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.6.0
atom-minify, v0.3.1
emmet, v2.3.12
file-icons, v1.6.9
linter, v1.4.3
linter-jshint, v1.1.5
php-twig, v4.0.0
pigments, v0.12.0
project-manager, v2.0.0
sync-settings, v0.6.0
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by eljenso** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Ubuntu 14.04.3
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.0.0


### Stack Trace

Uncaught Error: Cannot find module './project-manager-view'

```
At module.js:330

Error: Cannot find module './project-manager-view'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at atom-workspace.subscriptions.add.atom.commands.add.project-manager:toggle (/home/eljenso/.atom/packages/project-manager/lib/project-manager.coffee:79:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)
```

### Commands

```
     -1:47.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:47.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:47.3.0 editor:indent (atom-text-editor.editor.is-focused)
  3x -1:46.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:45.3.0 core:paste (atom-text-editor.editor.is-focused)
     -1:44.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:43.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:43.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:42.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:42.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:36.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:36.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:36.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:35.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:23.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui.find-visible)
     -0:00.6.0 project-manager:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "metrics",
      "wrap-guide"
    ]
  },
  "project-manager": {}
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
build, v0.45.0
color-picker, v2.0.11
editorconfig, v1.1.1
highlight-selected, v0.10.1
language-docker, v1.1.3
language-latex, v0.6.1
latexer, v0.2.4
linter, v1.4.3
monokai, v0.18.0
project-manager, v2.0.0

# Dev
No dev packages
```

**Comment by danielbrodin** [comment]
This is a rest from the last version. Restarting Atom should solve this

**Comment by chazzlabs** [comment]
Restarting Atom resolved this for me.  Thanks!

**Comment by ymatuhin** [comment]
Me too. Thanks 😊

**Comment by eljenso** [comment]
Restarting fixed this for me too.

**Comment by danielbrodin** [comment]
Great :)
