### ISSUE TITLE
Uncaught Error: watch ENOSPC

### ISSUE THREAD

**Issue by Draka** [danielbrodin/atom-project-manager#142]
[Enter steps to reproduce below:]

1. Open Atom

**Atom Version**: 1.0.11
**System**: Ubuntu 15.04
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.4.0

### Stack Trace

Uncaught Error: watch ENOSPC

```
At fs.js:1228

Error: watch ENOSPC
    at exports._errnoException (util.js:734:11)
    at FSWatcher.start (fs.js:1228:11)
    at Object.fs.watch (fs.js:1254:11)
    at DB.module.exports.DB.subscribeToProjectsFile (/home/draka/.atom/packages/project-manager/lib/db.coffee:151:36)
    at DB.subscribeToProjectsFile (/home/draka/.atom/packages/project-manager/lib/db.coffee:3:61)
    at /home/draka/.atom/packages/project-manager/lib/db.coffee:28:26
    at FSReqWrap.cb [as oncomplete] (fs.js:209:19)
```

### Commands

```
     -0:01.0 project-manager:list-projects (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-jshint"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
autocomplete-modules, v1.1.0
emmet, v2.3.12
file-icons, v1.6.9
highlight-selected, v0.10.1
jshint, v1.6.1
language-nginx, v0.5.4
less-autocompile, v1.0.0
less-compiler, v0.6.2
minimap, v4.13.2
node-debugger, v1.1.8
php-cs-fixer, v2.4.0
project-manager, v2.4.0
wakatime, v4.0.16

# Dev
No dev packages
```

**Comment by danielbrodin** [comment]
I think this has to do with to many files being watched on your system. Try looking up `max_user_watches` and increase it.
Will see if I can detect the error though and add a notification about it.

**Comment by Draka** [comment]
The error was: shortage of space on the hard disk, I sorry
