### ISSUE TITLE
Uncaught Error: Cannot find module './project-manager-add-view'

### ISSUE THREAD

**Issue by koichi-ezato** [danielbrodin/atom-project-manager#149]
[Enter steps to reproduce below:]

1. Add Project Folder.
2. Save Project the folder. Then show error message.

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.5.1

### Stack Trace

Uncaught Error: Cannot find module './project-manager-add-view'

```
At module.js:330

Error: Cannot find module './project-manager-add-view'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at atom-workspace.subscriptions.add.atom.commands.add.project-manager:save-project (/Users/koichi-ezato/.atom/packages/project-manager/lib/project-manager.coffee:66:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -7:52.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -7:49.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:45.7.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:43.4.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -7:42.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -7:41.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -7:37.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -7:29.6.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -7:27.9.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -7:27.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -7:20.1.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -7:18.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -7:17.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -7:16.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:01.1.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:41.4.0 project-manager:save-project (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "projectHome": "/Users/koichi-ezato/project"
  }
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.4.3
autocomplete-php, v0.3.7
autocomplete-python, v0.5.3
autocomplete-ruby, v0.1.0
autocomplete-sass, v0.1.0
file-icons, v1.6.9
git-log, v0.4.1
node-debugger, v1.1.8
project-manager, v2.5.1
tualo-git-context, v0.6.16

# Dev
No dev packages
```

**Comment by danielbrodin** [comment]
I guess you have updated from a 1.x version? Reload atom and it will work again.

**Comment by koichi-ezato** [comment]
I try to restart atom. It now works correctly. 
Thank you for your comment.
