### ISSUE TITLE
Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by T-Grave** [danielbrodin/atom-project-manager#156]
I've been getting this error every time I try to save a new project, couldn't find an existing issue yet.

**Atom Version**: 1.0.19
**System**: elementary OS
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.6.1

### Stack Trace

Uncaught TypeError: object is not a function

```
At /home/robin/.atom/packages/project-manager/lib/project-manager.js:49

TypeError: object is not a function
  at atom-workspace.projectManagerSaveProject (/home/robin/.atom/packages/project-manager/lib/project-manager.js:39:28)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:245:29)
  at /opt/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:245:29)
  at /opt/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:03.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:01.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 project-manager:save-project (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.12
emmet, v2.3.13
language-babel, v0.15.4
linter-jshint, v1.2.0
linter-scss-lint, v2.2.0
meteor-api, v2.20.0
pigments, v0.15.0
project-manager, v2.6.1

# Dev
No dev packages
```

**Comment by danielbrodin** [comment]
Have you tried reloading Atom or removing the `projects.cson` file?

**Comment by T-Grave** [comment]
I've had this issue for quite a while (at least a month) so several reboots have taken place since then. (and thus atom reloads too). Removed the projects.cson file just now but I still get the same error.

**Comment by danielbrodin** [comment]
I can't reproduce it so maybe has something to do with your OS. Does the error come when you trigger `project manager: save project` that shows the input field, or after you press enter to confirm and save the project?

**Comment by T-Grave** [comment]
It comes when I trigger ```project manager: save project```

My colleague who's sitting next to me is using the same OS (and almost exact same environment really) and he has no issue saving projects. I'll see if reinstalling Atom helps.

**Comment by danielbrodin** [comment]
Did it help? Another thing is to remove the `compile-cache` and `storage` folders in `.atom` or where it's saved on your os

**Comment by T-Grave** [comment]
I fixed it by removing the package from my Atom installation and installing it again :)

Sorry for the delay in response and thanks for your help on the matter!

**Comment by danielbrodin** [comment]
Great that you got it working :)
