### ISSUE TITLE
Cannot find module 'fs-plus'

### ISSUE THREAD

**Issue by Mech7** [danielbrodin/atom-project-manager#158]
I get the following error after starting atom today

Failed to activate the project-manager package
Cannot find module 'fs-plus'

```
Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/cdekok/.atom/packages/project-manager/node_modules/season/lib/cson.js:8:8)
    at Object.<anonymous> (/Users/cdekok/.atom/packages/project-manager/node_modules/season/lib/cson.js:262:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

**Comment by danielbrodin** [comment]
Is this still an issue? Sounds like something got messed up in Atom

**Comment by Mech7** [comment]
I guess upgrade to el capitan messed it up somehow if i delete the entire atom profile I don't have it anymore.
