### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is no l...

### ISSUE THREAD

**Issue by alflanagan** [danielbrodin/atom-project-manager#161]
[Enter steps to reproduce below:]

1. Installed coffee-compile package
2. Opened existing project

**Atom Version**: 1.0.19
**System**: "CentOS Linux
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.6.2

### Stack Trace

Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

```
At /usr/share/atom/resources/app.asar/src/panel-container-element.js:63

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
  at Error (native)
  at atom-panel-container.PanelContainerElement.panelRemoved (/usr/share/atom/resources/app.asar/src/panel-container-element.js:63:19)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PanelContainer.module.exports.PanelContainer.panelDestroyed (/usr/share/atom/resources/app.asar/src/panel-container.js:93:29)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Panel.module.exports.Panel.destroy (/usr/share/atom/resources/app.asar/src/panel.js:25:20)
  at ProjectsListView.close (/home/aflanagan/.atom/packages/project-manager/lib/projects-list-view.js:133:20)
  at ProjectsListView.confirmed (/home/aflanagan/.atom/packages/project-manager/lib/projects-list-view.js:126:14)
  at ProjectsListView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-li.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLOListElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -5:14 flex-tool-bar:edit-config-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-material-ui)
     -4:51.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -4:51.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:44.4.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:41.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:30.3.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -4:29.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -4:24.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:18.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:18.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:06.4.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
     -3:17.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:14.7.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-material-ui)
     -0:11.5.0 code-links:tmp-show-links (atom-text-editor.editor.mini.is-focused)
     -0:11.3.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -0:09.6.0 project-manager:list-projects (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
atom-macros, v0.5.2
atom-material-ui, v0.6.2
clipboard-plus, v0.5.1
code-links, v0.3.11
coffee-compile, v0.19.1
coffee-links, v0.1.0
column-select, v0.2.0
emmet, v2.3.13
file-icons, v1.6.10
flex-tool-bar, v0.5.0
language-javascript-semantic, v0.2.1
linter, v1.8.1
linter-coffeelint, v1.1.0
linter-pylint, v1.0.3
minimap, v4.13.4
minimap-git-diff, v4.1.8
minimap-linter, v1.0.0
project-manager, v2.6.2
slickedit-select, v1.6.0
tool-bar, v0.1.9

# Dev
No dev packages
```

**Comment by wonderbeyond** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 12.04.5
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.6.2


### Stack Trace

Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

```
At /usr/share/atom/resources/app.asar/src/panel-container-element.js:63

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at Error (native)
    at atom-panel-container.PanelContainerElement.panelRemoved (/usr/share/atom/resources/app.asar/src/panel-container-element.js:63:19)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at PanelContainer.module.exports.PanelContainer.panelDestroyed (/usr/share/atom/resources/app.asar/src/panel-container.js:93:29)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Panel.module.exports.Panel.destroy (/usr/share/atom/resources/app.asar/src/panel.js:25:20)
    at ProjectsListView.close (/home/wonder/.atom/packages/project-manager/lib/projects-list-view.js:104:18)
    at ProjectsListView.confirmed (/home/wonder/.atom/packages/project-manager/lib/projects-list-view.js:98:12)
    at ProjectsListView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)
```

### Commands

```
     -3:14.2.0 core:paste (atom-text-editor.editor.is-focused)
     -3:07.2.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -2:57.4.0 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.is-focused)
     -2:47.1.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -2:46.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:38.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:38.5.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -2:37.4.0 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.is-focused)
     -2:30.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -2:28.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:57.7.0 core:undo (atom-text-editor.editor.mini.is-focused)
     -0:06.9.0 project-manager:list-projects (atom-text-editor.editor.is-focused)
     -0:03.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:03.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:02.4.0 project-manager:list-projects (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -0:01.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".~*",
      "*.pyc"
    ],
    "projectHome": "/home/wonder/",
    "disabledPackages": [
      "clipboard-history",
      "auto-detect-indentation",
      "gulp-helper",
      "symbol-gen",
      "language-property-list",
      "linter-pylint",
      "atom-django"
    ]
  },
  "project-manager": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
django-atom, v0.2.4
emmet-simplified, v2.5.0
image-view, v0.55.0
japanese-wrap, v0.2.7
jquery-snippets, v11.0.0
language-html-swig, v2.0.1
language-nginx, v0.6.0
linter, v1.8.1
project-manager, v2.6.2

# Dev
No dev packages
```

**Comment by gfarrell** [comment]
[Enter steps to reproduce below:]

1. Open atom
2. Try to open an existing project

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.6.2


### Stack Trace

Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/panel-container-element.js:63

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
  at Error (native)
  at atom-panel-container.PanelContainerElement.panelRemoved (/Applications/Atom.app/Contents/Resources/app.asar/src/panel-container-element.js:63:19)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PanelContainer.module.exports.PanelContainer.panelDestroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/panel-container.js:93:29)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Panel.module.exports.Panel.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/panel.js:25:20)
  at ProjectsListView.close (/Users/gideon/.atom/packages/project-manager/lib/projects-list-view.js:133:20)
  at ProjectsListView.confirmed (/Users/gideon/.atom/packages/project-manager/lib/projects-list-view.js:126:14)
  at ProjectsListView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:15.1.0 project-manager:list-projects (atom-text-editor.editor.is-focused.vim-mode.insert-mode)
     -0:13.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.8.0 project-manager:list-projects (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:01.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-jshint",
      "background-tips",
      "bookmarks",
      "dev-live-reload",
      "spell-check",
      "autosave",
      "linter-phpcs",
      "atomtools",
      "remote-atom",
      "styleguide",
      "grunt-runner"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "projectHome": "/Users/gideon/Code"
  }
}
```

### Installed Packages

```coffee
# User
atom-jasmine, v0.6.0
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.2
atom-pair, v2.0.10
auto-indent, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-python, v0.6.2
better-handlebars, v0.1.1
build, v0.47.0
docblockr, v0.7.3
emmet, v2.3.13
highlight-selected, v0.10.1
language-babel, v0.15.7
language-blade, v0.16.0
language-docker, v1.1.3
laravel, v0.7.0
linter, v1.8.1
linter-csslint, v1.1.0
linter-eslint, v3.1.1
linter-jsonlint, v1.0.1
linter-markdown, v1.2.1
linter-php, v1.0.5
linter-pylint, v1.0.3
php-twig, v4.0.0
project-manager, v2.6.2
react, v0.12.10
refactor, v0.6.0
remote-edit, v1.8.21
svg-preview, v0.6.1
vim-mode, v0.61.0
wakatime, v5.0.0

# Dev
No dev packages
```

**Comment by OctoD** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 15.04
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.6.2


### Stack Trace

Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

```
At /usr/share/atom/resources/app.asar/src/panel-container-element.js:63

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
  at Error (native)
  at atom-panel-container.PanelContainerElement.panelRemoved (/usr/share/atom/resources/app.asar/src/panel-container-element.js:63:19)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PanelContainer.module.exports.PanelContainer.panelDestroyed (/usr/share/atom/resources/app.asar/src/panel-container.js:93:29)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Panel.module.exports.Panel.destroy (/usr/share/atom/resources/app.asar/src/panel.js:25:20)
  at ProjectsListView.close (/home/octod/.atom/packages/project-manager/lib/projects-list-view.js:133:20)
  at ProjectsListView.confirmed (/home/octod/.atom/packages/project-manager/lib/projects-list-view.js:126:14)
  at ProjectsListView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -6:02.0 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -6:01.1.0 pane:show-item-4 (atom-text-editor.editor.is-focused)
     -6:00.3.0 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -5:59.1.0 pane:show-item-4 (atom-text-editor.editor.is-focused)
     -3:14.4.0 editor:move-to-next-subword-boundary (atom-text-editor.editor.is-focused)
     -3:13.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -3:12.5.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -3:12.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:10.8.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:06.8.0 project-manager:list-projects (atom-text-editor.editor.is-focused)
  5x -0:06.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:05.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  6x -0:04.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  3x -0:02.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "advanced-new-file"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Stylus, v1.2.1
atom-jade, v0.3.0
atom-prettify, v0.1.3
atom-typescript, v7.4.1
atom-yeoman, v0.3.15
color-picker, v2.0.13
docblockr, v0.7.3
emmet, v2.3.13
grunt-runner, v0.11.0
json-schema, v0.1.15
language-aspx, v0.4.0
language-cshtml, v0.1.1
linter, v1.8.1
minimap, v4.13.4
omnisharp-atom, v0.24.16
pigments, v0.17.1
pretty-json, v0.4.1
project-manager, v2.6.2
react, v0.12.10

# Dev
No dev packages
```

**Comment by caseywebdev** [comment]
I'm still seeing this error in `2.6.3`

**Comment by dobosgy** [comment]
The same here in 2.6.3. The error started today.

**Comment by gfarrell** [comment]
Likewise

**Comment by say2joe** [comment]
Ditto.

**Comment by rdbinteractive** [comment]
Same here.

**Comment by mcphailtom** [comment]
ditto

**Comment by okonomiyaki3000** [comment]
:+1:

**Comment by danielbrodin** [comment]
Just got the error myself for the first time, but I have no idea how it happened. Can anyone reproduce it and give me a step by step guide?

**Comment by rdbinteractive** [comment]
On Windows: Alt+Shift+P arrow key to switch project. Select project with either the mouse or by hitting Enter. At least, that's how it's happening here.

**Comment by tungdt-90** [comment]
Same here for me:

Alt+Shift+P => choose a project in list => Click or Enter => The error notification shows up.

**Comment by JSn1nj4** [comment]
Same as @rdbinteractive and @tungdt-90.

**Comment by hedefalk** [comment]
+1 Seems to still work though

**Comment by diogosg** [comment]
+1

Alt+Shift+P => choose a project in list => Click or Enter => The error notification shows up.

**Comment by JohnRoach** [comment]
+1

Alt+Shift+P => choose a project in list => Click or Enter => The error notification shows up.

**Comment by ignism** [comment]
updated to latest version, I still have this issue - however apart from the error notification all seems to work fine.

**Comment by tungdt-90** [comment]
Sounds strange, i can confirm that the issue was solved after i update to 2.6.4. 

And before that, everything worked fine for me even when the error notification showed up.

**Comment by ignism** [comment]
Ah, my bad. I completely closed Atom and restarted. Can confirm this issue is solved for me now. Thanks for this great package!

**Comment by JSn1nj4** [comment]
Thanks for the work. New version works as expected.

**Comment by rdbinteractive** [comment]
Perfect! Thank you for the update!
