### ISSUE TITLE
Failed to activate the project-manager package

### ISSUE THREAD

**Issue by makmonty** [danielbrodin/atom-project-manager#189]
[Enter steps to reproduce below:]

1. Open Atom

**Atom Version**: 1.3.0
**System**: Ubuntu 15.10
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.7.3

### Stack Trace

Failed to activate the project-manager package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/angel/.atom/packages/project-manager/node_modules/season/lib/cson.js:8:8)
    at Object.<anonymous> (/home/angel/.atom/packages/project-manager/node_modules/season/lib/cson.js:262:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/angel/.atom/packages/project-manager/lib/db.js:3:29)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/angel/.atom/packages/project-manager/lib/projects.js:3:29)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Function.loadProject (/home/angel/.atom/packages/project-manager/lib/project-manager.js:64:16)
    at Function.activate (/home/angel/.atom/packages/project-manager/lib/project-manager.js:60:10)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:170:19)
    at /opt/atom/resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:92:15)
    at /opt/atom/resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:517:21)
    at /opt/atom/resources/app.asar/src/package-manager.js:499:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-beautify",
      "vim-mode",
      "filetype-color",
      "atom-color-highlight",
      "fonts"
    ]
  },
  "project-manager": {}
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
color-picker, v2.0.14
file-icons, v1.6.14
highlight-selected, v0.11.1
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-csslint, v1.2.0
linter-js-yaml, v1.2.5
linter-jshint, v1.2.2
linter-sass-lint, v0.6.3
minimap, v4.19.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
pigments, v0.19.7
project-manager, v2.7.3

# Dev
No dev packages
```

**Comment by danielbrodin** [comment]
I guess something failed during the install so that the fs-plus didn't get installed. I would try removing the package and install it again.
