### ISSUE TITLE
Uncaught Error: Cannot find module 'mixto'

### ISSUE THREAD

**Issue by rdeavila** [danielbrodin/atom-project-manager#196]
[Enter steps to reproduce below:]

1. Open Atom
2. Press Cmd+Ctrl+p

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.2
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.7.6

### Stack Trace

Uncaught Error: Cannot find module 'mixto'

```
At module.js:338

Error: Cannot find module 'mixto'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rodrigo/.atom/packages/project-manager/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/node_modules/emissary/node_modules/property-accessors/lib/property-accessors.js:6:11)
    at Object.<anonymous> (/Users/rodrigo/.atom/packages/project-manager/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/node_modules/emissary/node_modules/property-accessors/lib/property-accessors.js:74:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rodrigo/.atom/packages/project-manager/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/behavior.js:9:23)
    at Object.<anonymous> (/Users/rodrigo/.atom/packages/project-manager/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/behavior.js:120:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rodrigo/.atom/packages/project-manager/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/helpers.js:5:14)
    at Object.<anonymous> (/Users/rodrigo/.atom/packages/project-manager/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/helpers.js:55:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rodrigo/.atom/packages/project-manager/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/emissary.js:4:13)
```

### Commands

```
     -0:01.1.0 project-manager:list-projects (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-beautify",
      "editorconfig",
      "file-icons",
      "html-entities",
      "language-chef"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/rodrigo",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
project-manager, v2.7.6

# Dev
No dev packages
```

**Comment by danielbrodin** [comment]
Seems like a node module is missing. Have you tried to reinstall the package?

**Comment by CharlesHamel** [comment]
Add had exactly the same error installing it by cloning the repo and `apm link .` I solved the problem by doing `apm install minimap`
