### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by awakekat** [danielbrodin/atom-project-manager#206]
I just updated to the new release as of 3/27 and here is the error after updating on current mac and atom versions:
Uncaught TypeError: _projects2.default.getAll is not a function
/Users/Mini/.atom/packages/project-manager/lib/projects-list-view.js:69
Hide Stack Trace
TypeError: _projects2.default.getAll is not a function
    at ProjectsListView.toggle (/Users/Mini/.atom/packages/project-manager/lib/projects-list-view.js:69:16)
    at atom-workspace.projectManagerListProjects (/Users/Mini/.atom/packages/project-manager/lib/project-manager.js:18:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)

**Comment by awakekat** [comment]
Sorry - I restarted Atom and all is well.

**Comment by awakekat** [comment]
Sorry - I restarted Atom and all is well.
You can close this.
