### ISSUE TITLE
Uncaught TypeError: _projects2.default.getAll is not a function

### ISSUE THREAD

**Issue by ashw7n** [danielbrodin/atom-project-manager#207]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.8.0

### Stack Trace

Uncaught TypeError: _projects2.default.getAll is not a function

```
At /Users/araveendrann/.atom/packages/project-manager/lib/projects-list-view.js:69

TypeError: _projects2.default.getAll is not a function
    at ProjectsListView.toggle (/Users/araveendrann/.atom/packages/project-manager/lib/projects-list-view.js:69:16)
    at atom-workspace.projectManagerListProjects (/Users/araveendrann/.atom/packages/project-manager/lib/project-manager.js:18:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:06.4.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
  3x -0:02.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 project-manager:list-projects (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-go, v1.0.5
autocomplete-python, v1.7.2
builder-go, v1.0.0
environment, v1.2.0
go-config, v1.1.2
go-get, v1.0.2
go-plus, v4.1.0
gofmt, v1.1.3
gometalinter-linter, v1.1.0
gorename, v1.0.0
linter, v1.11.4
linter-pep8, v1.2.1
navigator-godef, v1.0.2
nerd-treeview, v0.4.2
project-manager, v2.8.0
project-plus, v0.8.0
python-tools, v0.6.7
tester-go, v1.0.3
vim-mode, v0.65.0
vim-mode-visual-block, v0.2.15

# Dev
No dev packages
```

**Comment by skabrock** [comment]
Same issue has appeared today.
Atom 1.5.3 / OS X 10.11.4
Installed packages:
├── auto-reveal-in-sidebar@0.8.0
├── autoprefixer@3.2.0
├── color-picker@2.1.1
├── ctrl-last-tab@0.3.0
├── dev-lorem@0.1.2
├── emmet@2.4.3
├── emmet-snippets-compatibility@1.0.4
├── git-plus@5.13.0
├── language-haml@0.23.15
├── livereload@0.4.4
├── pigments@0.26.0
├── project-manager@2.8.0
├── run-in-browser@0.1.3
├── slim-language@2.2.0
├── synced-sidebar@0.4.3
└── tabs-to-spaces@1.0.2

**Comment by Frique** [comment]
Same in Atom 1.6.0, OSX 10.11.4

**Comment by GijsGoudzwaard** [comment]
+1

**Comment by rafawhs** [comment]
+1

Atom 1.6.0
OSX 10.11.4

├── Sublime-Style-Column-Selection@1.5.1
├── activate-power-mode@0.4.1
├── aligner@0.19.1
├── aligner-php@1.0.0
├── atom-wordpress@0.3.0
├── emmet@2.4.3
├── highlight-line@0.11.1
├── html-entities@0.4.0
├── linter@1.11.4
├── linter-jshint@2.0.3
├── linter-php@1.2.0
├── linter-phpcs@1.3.1
├── linter-phpmd@1.4.1
├── minimap@4.21.0
├── open-terminal-here@2.1.4
├── project-manager@2.8.0
├── seti-syntax@0.4.2
├── seti-ui@0.9.2
├── sk3ltn-syntax@2.0.0
└── wordpress-api@1.2.2

**Comment by bradpurchase** [comment]
+1

**Comment by eristoddle** [comment]
+1

**Comment by danielbrodin** [comment]
Reloading Atom will solve this

**Comment by manuelbieh** [comment]
Same here, after upgrading to 2.8.0 (Atom 1.6.0 on Windows 10)

**Comment by fayimora** [comment]
Restarting solved this for me too :smiley:
