### ISSUE TITLE
Failed to activate the project-manager package [Cannot find module 'underscore-plus']

### ISSUE THREAD

**Issue by vpakg** [danielbrodin/atom-project-manager#210]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: elementary OS
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.8.0

### Stack Trace

Failed to activate the project-manager package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
  at Module._resolveFilename (module.js:336:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/home/victor/.atom/packages/project-manager/lib/project.js:13:23)
  at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/home/victor/.atom/packages/project-manager/lib/projects.js:13:16)
  at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Function.activate (/home/victor/.atom/packages/project-manager/lib/project-manager.js:29:18)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:181:20)
  at /usr/share/atom/resources/app.asar/src/package.js:155:32
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
  at /usr/share/atom/resources/app.asar/src/package.js:148:26
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:145:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:526:21)
  at /usr/share/atom/resources/app.asar/src/package-manager.js:507:29
  at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:502:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:485:46)
  at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:688:21)
  at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
  at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
  at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)

```

**Comment by danielbrodin** [comment]
Something happened during the install so try reinstalling the package.
