### ISSUE TITLE
Uncaught Error: Cannot find module 'change-case'

### ISSUE THREAD

**Issue by hiberno** [danielbrodin/atom-project-manager#214]
1. Try to save a new project.

**Atom Version**: 1.6.2
**System**: linux 4.4.5-1-ARCH
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.9.5

### Stack Trace

Uncaught Error: Cannot find module 'change-case'

```
At module.js:338

Error: Cannot find module 'change-case'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/hiberno/.atom/packages/project-manager/lib/save-dialog.coffee:4:14)
    at Object.<anonymous> (/home/hiberno/.atom/packages/project-manager/lib/save-dialog.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at atom-workspace.projectManagerSaveProject (/home/hiberno/.atom/packages/project-manager/lib/project-manager.js:21:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:10.1.0 project-manager:list-projects (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
     -0:08.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:08.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:04.7.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 project-manager:save-project (atom-text-editor.editor.vim-mode.normal-mode)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "themes": [
      "isotope-ui",
      "atom-dark-fusion-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Parinfer, v1.14.0
atom-alignment, v0.12.1
atom-dark-fusion-syntax, v1.1.0
atomic-chrome, v0.3.0
change-case, v0.6.0
highlight-line, v0.11.1
highlight-selected, v0.11.2
isotope-ui, v2.7.1
language-latex, v0.6.1
language-rust, v0.4.6
linter, v1.11.4
linter-rust, v0.4.5
lisp-paredit, v0.5.3
minimap, v4.21.0
minimap-highlight-selected, v4.4.0
project-manager, v2.9.5
proto-repl, v1.1.7
proto-repl-charts, v0.3.2
racer, v0.18.0
tool-bar, v0.4.0
vim-mode, v0.65.0
vim-surround, v0.8.1
wordcount, v2.6.0

# Dev
No dev packages
```

**Comment by danielbrodin** [comment]
Sorry, forgot to include it. Should be able to run an update to fix it.

**Comment by railto** [comment]
Any idea as to how long before the update will be available? have tried updating but still having same issue, worth noting that only installed this plugin after the issue was reported.

**Comment by danielbrodin** [comment]
apm seemed to screw up with publishing. Should work now.

**Comment by hiberno** [comment]
@danielbrodin Can confirm that it works now. Thanks! :)

**Comment by railto** [comment]
Yup, all good now, thank's @danielbrodin

**Comment by lelivero** [comment]
I confirm it's working again. Thanks @danielbrodin !
