### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by matteo-webdev** [danielbrodin/atom-project-manager#216]
Steps to reproduce the error:
1. put the project.cson I enclose in the ~/.atom folder
2. open it, edit it, save it and get the error

If, in the project.cson, there is just one project, the error doesn't happen

**Atom Version**: 1.6.2
**System**: Mac OS X 10.10.5
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.9.7
### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Users/mnicoletti/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:126

RangeError: Maximum call stack size exceeded
    at Array.map (native)
    at Object.plus.deepClone (/Users/mnicoletti/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:126:23)
    at /Users/mnicoletti/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:132:31
    at Object.plus.mapObject (/Users/mnicoletti/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:287:17)
    at Object.plus.deepClone (/Users/mnicoletti/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:130:21)
```

The last three lines are repeated indefinitely in the stack trace...

Here is my project.cson:

```
chiantibanca_responsive:
  title: "chiantibanca.it responsive"
  paths: [
    "/Users/mnicoletti/progetti/chiantibanca/chiantibanca.it"
    "/Users/mnicoletti/progetti/chiantibanca/chiantibanca.it/site/frontend"
    "/Users/mnicoletti/progetti/chiantibanca/chiantibanca.it/site/backend"
    "/Users/mnicoletti/progetti/chiantibanca/chiantibanca.it/backoffice"
  ]
clickforshop_frontend:
  title: "clickforshop.it responsive (solo frontend)"
  paths: [
    "/Users/mnicoletti/progetti/tacabanda/clickforshop_frontend"
  ]
ecommercebase_responsive:
  title: "eCommerce base responsive"
  paths: [
    "/Users/mnicoletti/progetti/ecommercebase/ecommercebase"
    "/Users/mnicoletti/progetti/ecommercebase/ecommercebase/site/frontend"
    "/Users/mnicoletti/progetti/ecommercebase/ecommercebase/site/backend"
    "/Users/mnicoletti/progetti/ecommercebase/ecommercebase/backoffice"
  ]
gioiapura_responsive:
  title: "gioiapura.it responsive"
  paths: [
    "/Users/mnicoletti/progetti/fb/gioiapura_responsive"
    "/Users/mnicoletti/progetti/fb/gioiapura_responsive/site/frontend"
    "/Users/mnicoletti/progetti/fb/gioiapura_responsive/site/backend"
    "/Users/mnicoletti/progetti/fb/gioiapura_responsive/backoffice"
  ]
motorama_responsive:
  title: "motorama.it responsive"
  paths: [
    "/Users/mnicoletti/progetti/motorama/motorama_responsive"
    "/Users/mnicoletti/progetti/motorama/motorama_responsive/site/frontend"
    "/Users/mnicoletti/progetti/motorama/motorama_responsive/site/backend"
    "/Users/mnicoletti/progetti/motorama/motorama_responsive/backoffice"
  ]
outletmoto_responsive:
  title: "outletmoto.eu responsive"
  paths: [
    "/Users/mnicoletti/progetti/outletmoto/outletmoto.eu"
    "/Users/mnicoletti/progetti/outletmoto/outletmoto.eu/site/frontend"
    "/Users/mnicoletti/progetti/outletmoto/outletmoto.eu/site/backend"
    "/Users/mnicoletti/progetti/outletmoto/outletmoto.eu/backoffice"
  ]
```

**Comment by matteo-webdev** [comment]
Ok, I found a solution. Totally by luck but here it goes: removing the _ from the project id doesn't throw the error anymore.

i.e. with this project.cson everything works fine:
```
chiantibanca:
  title: "chiantibanca.it"
  paths: [
    "/Users/mnicoletti/progetti/chiantibanca/chiantibanca.it"
    "/Users/mnicoletti/progetti/chiantibanca/chiantibanca.it/site/frontend"
    "/Users/mnicoletti/progetti/chiantibanca/chiantibanca.it/site/backend"
    "/Users/mnicoletti/progetti/chiantibanca/chiantibanca.it/backoffice"
  ]
clickforshop:
  title: "clickforshop.it (solo frontend)"
  paths: [
    "/Users/mnicoletti/progetti/tacabanda/clickforshop_frontend"
  ]
ecommercebase:
  title: "eCommerce base"
  paths: [
    "/Users/mnicoletti/progetti/ecommercebase/ecommercebase"
    "/Users/mnicoletti/progetti/ecommercebase/ecommercebase/site/frontend"
    "/Users/mnicoletti/progetti/ecommercebase/ecommercebase/site/backend"
    "/Users/mnicoletti/progetti/ecommercebase/ecommercebase/backoffice"
  ]
gioiapura:
  title: "gioiapura.it"
  paths: [
    "/Users/mnicoletti/progetti/fb/gioiapura_responsive"
    "/Users/mnicoletti/progetti/fb/gioiapura_responsive/site/frontend"
    "/Users/mnicoletti/progetti/fb/gioiapura_responsive/site/backend"
    "/Users/mnicoletti/progetti/fb/gioiapura_responsive/backoffice"
  ]
motorama:
  title: "motorama.it"
  paths: [
    "/Users/mnicoletti/progetti/motorama/motorama_responsive"
    "/Users/mnicoletti/progetti/motorama/motorama_responsive/site/frontend"
    "/Users/mnicoletti/progetti/motorama/motorama_responsive/site/backend"
    "/Users/mnicoletti/progetti/motorama/motorama_responsive/backoffice"
  ]
outletmoto:
  title: "outletmoto.eu"
  paths: [
    "/Users/mnicoletti/progetti/outletmoto/outletmoto.eu"
    "/Users/mnicoletti/progetti/outletmoto/outletmoto.eu/site/frontend"
    "/Users/mnicoletti/progetti/outletmoto/outletmoto.eu/site/backend"
    "/Users/mnicoletti/progetti/outletmoto/outletmoto.eu/backoffice"
  ]
```
Still I think it worths to correct this bug.

**Comment by kisexu** [comment]
Atom Version: 1.6.2
System: Mac OS X 10.11.3
project-manager:   v2.9.3

<img width="456" alt="2016-04-26 16 35 49" src="https://cloud.githubusercontent.com/assets/1040190/14812170/89c750ec-0bce-11e6-9ba8-73825d138273.png">

**Comment by danielbrodin** [comment]
@kisexu updating the package will fix it.

**Comment by darylknight** [comment]
I removed all the underscores - it still crashes. Package is up to date.
