### ISSUE TITLE
Uncaught TypeError: projects.getCurrent is not a function

### ISSUE THREAD

**Issue by kiritani05** [danielbrodin/atom-project-manager#241]
i can't save project.

[Enter steps to reproduce below:]

1. package>project Manager > Save Project
2. Error!

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.5
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.9.7

### Stack Trace

Uncaught TypeError: projects.getCurrent is not a function

```
At /Users/user-name/.atom/packages/project-manager/lib/save-dialog.coffee:23

TypeError: projects.getCurrent is not a function
    at new SaveDialog (/Users/user-name/.atom/packages/project-manager/lib/save-dialog.coffee:23:14)
    at atom-workspace.projectManagerSaveProject (/Users/user-name/.atom/packages/project-manager/lib/project-manager.js:23:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -7:41.4.0 project-manager:save-project (atom-text-editor.editor.is-focused)
     -4:43.1.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -4:23.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:12.6.0 core:close (div.package-detail.panels-item)
     -0:00.8.0 project-manager:save-project (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
autocomplete-paths, v1.0.2
color-picker, v2.2.2
emmet, v2.4.3
file-icons, v1.7.17
git-history, v3.2.0
git-log, v0.4.1
highlight-column, v0.5.1
highlight-selected, v0.11.2
japanese-menu, v1.8.0
language-slim, v0.5.0
minimap, v4.24.7
minimap-autohide, v0.10.1
pigments, v0.31.2
project-manager, v2.9.7

# Dev
No dev packages
```

**Comment by danielbrodin** [comment]
Your issue should hopefully be fixed in the new release
