### ISSUE TITLE
3.0 throws error on "switch project"

### ISSUE THREAD

**Issue by smlombardi** [danielbrodin/atom-project-manager#250]
I hit the keyboard command to bring up the project switcher and got this error:

**Atom Version**: 1.11.0-beta5
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v3.0.0

### Stack Trace

Uncaught Error: Cannot find module './projects-list-view'

```
At module.js:341

Error: Cannot find module './projects-list-view'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at atom-workspace.projectManagerListProjects (/Users/stevelombardi/.atom/packages/project-manager/lib/project-manager.js:28:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -8:46.3.0 emmet:toggle-comment (atom-text-editor.editor.is-focused)
     -8:46.3.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -8:44.8.0 core:save (atom-text-editor.editor.is-focused)
  4x -1:18.7.0 core:undo (atom-text-editor.editor.is-focused)
  4x -1:15.7.0 core:redo (atom-text-editor.editor.is-focused)
     -1:12.4.0 core:undo (atom-text-editor.editor.is-focused)
     -1:09.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:18.9.0 platformio-ide-terminal:close (atom-text-editor.editor.is-focused)
     -0:15.5.0 project-manager:list-projects (atom-text-editor.editor.is-focused)
  2x -0:08.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:05.1.0 core:close (atom-text-editor.editor.is-focused)
     -0:00.0 project-manager:list-projects (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.tinted-tab-bar.compact-tab-bar.no-tab-min-width.panel-contrast.use-animations.compact-tree-view.blend-tree-view.paint-cursor.theme-atom-material-syntax.theme-atom-material-ui.has-custom-icons)
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "disabledPackages": [
      "wrap-guide",
      "preview-tabs",
      "autocomplete-snippets",
      "gulp-control",
      "deprecation-cop",
      "linter-jscs",
      "linter-jshint",
      "autocomplete-paths"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "node_modules"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "useCustomTitleBar": true
  },
  "project-manager": {
    "closeCurrent": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined (inactive)
angularjs, v0.3.5 (active)
atom-beautify, v0.29.11 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-material-syntax, v0.4.6 (active)
atom-material-ui, v1.3.6 (active)
atom-typescript, v10.1.6 (active)
autoprefixer, v3.2.1 (inactive)
change-case, vundefined (active)
css-comb, v2.5.0 (active)
double-tag, v0.4.0 (active)
duotone-light-syntax, v1.0.0 (inactive)
editorconfig, v1.4.1 (active)
emmet, v2.4.3 (active)
escape-utils, v0.5.3 (inactive)
file-icons, v1.7.19 (active)
firewatch-syntax, v1.0.1 (inactive)
git-plus, v5.17.0 (inactive)
github-atom-light-syntax, v0.2.0 (inactive)
gruvbox-plus-syntax, v1.2.5 (inactive)
inline-markdown-images, v0.1.1 (active)
language-svg, v0.9.0 (active)
less-than-slash, v0.16.0 (active)
linter, v1.11.16 (active)
linter-eslint, v7.3.0 (active)
linter-htmlhint, v1.3.0 (active)
linter-jsonlint, v1.3.0 (active)
linter-less, v2.6.0 (active)
linter-stylelint, v3.2.1 (active)
linter-tslint, v0.11.1 (active)
livestyle-atom, v0.2.7 (active)
nucleus-dark-ui, v0.9.5 (inactive)
pigments, v0.34.0 (active)
platformio-ide-terminal, v2.2.0 (active)
project-manager, v3.0.0 (active)
selection-counter, v1.0.0 (active)
seti-icons, v1.3.3 (active)
snippet-generator, v0.3.2 (inactive)
sort-lines, v0.14.0 (inactive)
standard-formatter, v2.0.1 (active)
stylefmt, v3.1.2 (inactive)
sync-settings, v0.7.2 (active)
tag, v0.4.0 (active)
title-case, v0.4.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by danielbrodin** [comment]
Have you restarted atom?

**Comment by hectorleiva** [comment]
I can confirm restarting Atom fixes this issue.
