### ISSUE TITLE
Uncaught TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by xdemocle** [danielbrodin/atom-project-manager#285]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v3.3.2

### Stack Trace

Uncaught TypeError: Cannot read property 'open' of undefined

```
At /Users/democle/.atom/packages/project-manager/lib/views/projects-list-view.js:116

TypeError: Cannot read property 'open' of undefined
    at ProjectsListView.confirmed (/Users/democle/.atom/packages/project-manager/lib/views/projects-list-view.js:116:7)
    at ProjectsListView.module.exports.SelectListView.confirmSelection (/Users/democle/.atom/packages/project-manager/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-li.<anonymous> (/Users/democle/.atom/packages/project-manager/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.jQuery.event.dispatch (/Users/democle/.atom/packages/project-manager/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/Users/democle/.atom/packages/project-manager/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -7:12.1.0 core:undo (atom-text-editor.editor.is-focused)
     -7:11.3.0 core:redo (atom-text-editor.editor.is-focused)
     -7:09.1.0 core:undo (atom-text-editor.editor.is-focused)
  4x -7:07.1.0 core:redo (atom-text-editor.editor.is-focused)
     -7:05.8.0 core:undo (atom-text-editor.editor.is-focused)
     -7:05.4.0 core:save (atom-text-editor.editor.is-focused)
     -7:03.4.0 core:redo (atom-text-editor.editor.is-focused)
     -7:02.2.0 core:undo (atom-text-editor.editor.is-focused)
     -2:28.8.0 core:close (atom-text-editor.editor.is-focused)
     -2:23.3.0 core:copy (atom-text-editor.editor.is-focused)
     -2:22.5.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -2:22.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:21.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -2:21.6.0 core:delete (atom-text-editor.editor.is-focused)
     -2:21.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:14.7.0 project-manager:list-projects (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "projectHome": "/Users/democle/Documents/EnjoyItaly",
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "robin-hood-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angular-jonpapa-snippets, v0.7.0 (active)
angularjs, v0.3.5 (active)
atom-beautify, v0.29.13 (active)
atom-formatter-jsbeautify, v1.1.2 (active)
atom-jasmine, v0.8.1 (active)
atom-jshint, v2.0.0 (active)
color-tabs, v0.1.8 (active)
docblockr, v0.8.7 (active)
editorconfig, v1.5.3 (active)
language-jasmin, v0.2.0 (active)
language-ngdoc, v0.1.0 (active)
livereload, v0.4.4 (active)
local-history, vundefined (active)
pinned-tabs, v0.4.1 (active)
project-manager, v3.3.2 (active)
robin-hood-syntax, v1.0.0 (active)
split-diff, v1.0.5 (inactive)
stash-tabs, v0.1.0 (active)
terminal-plus, v0.14.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by shadymoses** [comment]
I had the same issue after updating. Restarting atom fixed it for me.

**Comment by oriolmirosa** [comment]
I can confirm that the problem is when the package is updated to v3.3.2 and that the problem goes away when Atom is re-started.

**Comment by BarryThePenguin** [comment]
Looks like it's an update issue. I was able to reproduce this and saw that some of the previous package modules were still in use by atom. Maybe there is some additional tidy up that needs to happen when the package is deactivated during updates?

Others are having similar issues too 😞  msaraiva/atom-elixir#19

**Comment by marcerbil** [comment]
Can confirm that restarting Atom fixed it for me too

**Comment by danielbrodin** [comment]
> Maybe there is some additional tidy up that needs to happen when the package is deactivated during updates?

Yeah, probably. I guess it's hard to fix it for older versions, but probably something that should be looked at for the current version for future updates that could break something. Not sure what would have to be done, but the issue over at atom-elixir looked interesting as a starting point.

**Comment by xdemocle** [comment]
yes, after restart it fixed also for me.
Shall I close this issue? Or @danielbrodin you will take care?

**Comment by danielbrodin** [comment]
@xdemocle Happy to hear it worked after the restart 👍
