### ISSUE TITLE
Setting Theme Colors in projects.cson

### ISSUE THREAD

**Issue by bennypowers** [danielbrodin/atom-project-manager#304]
My theme has a toolbar colour setting, which I'd like to customise per-project. The following config does not affect the change in colour:

    {
      title: "ksy-building-fund"
      paths: [
        "/Users/benny/web/ux/ksy-building-fund"
      ]
      settings:
        "atom-material-ui":
          colors:
            abaseColor:
              red: 66
              green: 133
              blue: 244
              alpha: 1
            genAccent: true
    }

Perhaps my config is malformed?

**Comment by danielbrodin** [comment]
Does it work if you try changing `abaseColor` to `abaseColor: rgba(66,133,244,1)` instead?

**Comment by bennypowers** [comment]
[Enter steps to reproduce below:]

projects.cson:
```cson
  {
    title: "KSY Building Fund"
    group: "ux"
    paths: [
      "/Users/bennyp/web/ux/ksy-building-fund"
    ]
    icon: "icon-beaker"
    settings:
      "atom-material-ui":
        colors:
          abaseColor: rgba(66,133,244,1)
        genAccent: true
  }
```

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v3.3.3


### Stack Trace

Uncaught TypeError: Cannot read property 'first_line' of undefined

```
At /Users/bennyp/.atom/packages/project-manager/lib/stores/FileStore.js:94

TypeError: Cannot read property 'first_line' of undefined
    at Function.handleError (/Users/bennyp/.atom/packages/project-manager/lib/stores/FileStore.js:94:45)
    at /Users/bennyp/.atom/packages/project-manager/lib/stores/FileStore.js:44:21
    at transaction (/Users/bennyp/.atom/packages/project-manager/node_modules/mobx/lib/mobx.js:1390:23)
    at /Users/bennyp/.atom/packages/project-manager/lib/stores/FileStore.js:41:7
    at parseContents (/Users/bennyp/.atom/packages/project-manager/node_modules/season/lib/cson.js:111:9)
    at /Users/bennyp/.atom/packages/project-manager/node_modules/season/lib/cson.js:208:20
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

### Commands

```
     -0:59.3.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:59.2.0 core:paste (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
 12x -0:56.2.0 core:delete (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:53.4.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:52.9.0 core:select-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -0:48.3.0 core:delete (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:47.4.0 editor:move-to-end-of-word (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:46.8.0 editor:select-to-end-of-word (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:46.1.0 core:select-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:44.7.0 editor:move-to-end-of-word (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:44.3.0 editor:select-to-end-of-word (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:43.6.0 core:select-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:05.1.0 editor:select-to-end-of-word (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:02.6.0 core:delete (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:02.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:00.3.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "preview-plus",
      "notebook",
      "font-awesome-snippetset",
      "lines",
      "livereload",
      "recent-projects",
      "atom-ftp-editor",
      "atom-commander",
      "project-plus",
      "SFTP-deployment",
      "atom-ng-attr-hint",
      "atom-pair",
      "autocomplete-angular-material",
      "bob-ross-lipsum-atom",
      "remote-edit",
      "tabs-to-spaces",
      "angularjs",
      "atom-angular-material-snippets",
      "atom-wrap-in-tag",
      "dash",
      "keybinding-cheatsheet",
      "minimap",
      "ng2-snippets",
      "remote-sync",
      "angular2-snippets-atom",
      "linter-eslint",
      "jsonlint",
      "json-schema",
      "Remote-FTP",
      "atom-typescript",
      "terminal-plus",
      "htmlhint",
      "jshint",
      "markdown-themeable-pdf"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "node_modules",
      "bower_components"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/bennyp/web",
    "telemetryConsent": "limited",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ],
    "useCustomTitleBar": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined (inactive)
angular2-snippets-atom, v0.7.0 (inactive)
angularjs, v0.3.5 (inactive)
angularjs-styleguide-snippets, v0.9.1 (active)
atom-angular-material-snippets, v1.3.0 (inactive)
atom-beautify, v0.29.14 (active)
atom-commander, v0.8.5 (inactive)
atom-ftp-editor, v0.5.0 (inactive)
atom-html-preview, v0.1.22 (active)
atom-live-server, v1.2.5 (active)
atom-material-contrast-syntax, v0.2.0 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (active)
atom-material-ui, v1.3.8 (active)
atom-ng-attr-hint, v2.1.0 (inactive)
atom-pair, v2.0.10 (inactive)
atom-typescript, v10.1.13 (inactive)
atom-wrap-in-tag, v0.6.0 (inactive)
atomic-chrome, v0.3.0 (active)
auto-update-packages, v1.0.1 (active)
autocomplete-angular-material, v0.4.0 (inactive)
autocomplete-html-entities, v0.1.0 (active)
autocomplete-modules, v1.6.7 (active)
chrome-color-picker, v0.8.0 (inactive)
clone-cursor, v1.1.2 (active)
dash, v1.7.0 (inactive)
docblockr, v0.9.1 (active)
docker, v0.7.0 (inactive)
emmet, v2.4.3 (active)
expand-selection-to-quotes, v0.11.0 (active)
file-icons, v1.7.25 (active)
firewatch-syntax, v1.0.1 (inactive)
font-awesome-snippetset, v0.0.6 (inactive)
genesis-ui, v0.5.0 (inactive)
git-plus, v5.29.1 (active)
git-time-machine, v1.5.4 (inactive)
greti-syntax, v0.6.0 (inactive)
gruvbox-syntax, v2.4.1 (inactive)
highlight-column, v0.5.1 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
html-id-class-snippets, v1.4.1 (active)
htmlhint, v1.1.4 (inactive)
imdone-atom, v2.0.19 (active)
imdone-atom-github, v0.1.11 (active)
indent-guide-improved, v1.4.11 (active)
jshint, v1.8.6 (inactive)
json-schema, v0.1.15 (inactive)
jsonlint, v1.1.4 (inactive)
keybinding-cheatsheet, v0.1.1 (inactive)
language-docker, v1.1.7 (active)
language-fish-shell, v1.0.5 (active)
less-than-slash, v0.16.0 (active)
lines, v0.13.1 (inactive)
linter, v1.11.18 (active)
linter-csslint, v1.3.3 (active)
linter-docker, v0.1.4 (active)
linter-eslint, v8.0.0 (inactive)
linter-htmlhint, v1.3.1 (active)
linter-jshint, v3.0.2 (active)
linter-jsonlint, v1.3.0 (active)
linter-php, v1.3.1 (active)
linter-stylelint, v3.6.0 (active)
linter-tslint, v0.12.0 (active)
livereload, v0.4.4 (inactive)
markdown-pdf, v1.5.0 (inactive)
markdown-scroll-sync, v2.1.2 (active)
markdown-themeable-pdf, v1.2.0 (inactive)
markdown-toc, v0.4.1 (inactive)
material-syntax, v0.5.0 (inactive)
material-ui, v1.0.9 (inactive)
merge-conflicts, v1.4.4 (active)
metro-ui, v2.2.2 (inactive)
minimap, v4.25.7 (inactive)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
native-ui, v0.19.1 (inactive)
ng2-snippets, v0.2.2 (inactive)
notebook, v0.4.0 (inactive)
pigments, v0.37.0 (active)
platformio-ide-terminal, v2.2.2 (active)
polymer-ide, v0.2.2 (active)
polymer-snippets, v3.2.1 (inactive)
preview-plus, v1.2.7 (inactive)
project-manager, v3.3.3 (active)
project-plus, v0.9.0 (inactive)
recent-projects, v0.13.1 (inactive)
relative-numbers, v0.6.0 (active)
remote-edit, v1.8.24 (inactive)
Remote-FTP, v0.9.4 (inactive)
remote-sync, v4.1.5 (inactive)
sequential-number, v0.4.0 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.4.0 (inactive)
SFTP-deployment, v1.0.2 (inactive)
sort-lines, v0.14.0 (active)
split-diff, v1.1.0 (inactive)
state-of-nature-syntax, v0.1.0 (inactive)
sync-settings, v0.8.0 (active)
tabs-to-spaces, v1.0.2 (inactive)
tango-syntax, v0.4.1 (inactive)
terminal-plus, v0.14.5 (inactive)
todo-show, v1.8.0 (inactive)
toggle-quotes, v1.0.0 (inactive)
unity-dark-ui, v2.0.9 (inactive)
unity-ui, v2.1.7 (inactive)
vim-mode, v0.65.2 (active)
vim-surround, v0.8.1 (active)
wordpress-api, v1.2.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (active)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by bennypowers** [comment]
It works when I wrap the rgba value in quotes:

```cson
  {
    title: "KSY Building Fund"
    group: "ux"
    paths: [
      "/Users/bennyp/web/ux/ksy-building-fund"
    ]
    icon: "icon-beaker"
    settings:
      "atom-material-ui":
        colors:
          abaseColor: "rgba(66,133,244,1)";
        genAccent: true
  }
```

Super cool! and really useful if you're the visual type, helps keep projects sorted. I recommend you add this to "edit project" screen.

**Comment by bennypowers** [comment]
Hrm... color is set to the last referenced color in projects.cson for all windows, regardless of currently loaded project.

**Comment by danielbrodin** [comment]
It's a thing with Atom where it works to change settings without saving it, but as soon as you open the settings view, all settings are saved which will affect all windows. Haven't found a way to fix this. Settings that provide an api, like `editor.softTabs` could be fixed, but other than that I don't know of a solution.
