### ISSUE TITLE
Failed to activate the project-manager package

### ISSUE THREAD

**Issue by razhangwei** [danielbrodin/atom-project-manager#321]
**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Ubuntu 14.04.5
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package 3.3.3

### Stack Trace

Failed to activate the project-manager package

```
At _storesGitStore2.default is not a constructor

TypeError: _storesGitStore2.default is not a constructor
    at /packages/project-manager/lib/Manager.js:26:21)
    at /packages/project-manager/lib/Manager.js:156:17)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/project-manager/lib/project-manager.js:4:43)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-latex 0.7.1 
autocomplete-python 1.8.60 
docblockr 0.9.1 
Hydrogen 1.6.0 
language-julia 0.10.0 
language-latex 1.0.0 
last-cursor-position 0.9.0 
latex-completions 0.3.2 
linter 2.1.0 
linter-flake8 2.1.4 
linter-julia 0.7.1 
linter-pylint 1.2.2 
linter-ui-default 1.2.1 
minimap 4.26.8 
project-manager 3.3.3 
Remote-FTP 0.10.7 
sync-settings 0.8.1 
termination 0.5.0 
```

**Comment by AdamMarkowski** [comment]
**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package 3.3.4


### Stack Trace

Failed to activate the project-manager package

```
At Cannot find module 'mobx'

Error: Cannot find module 'mobx'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/project-manager/lib/project-manager.js:11:13)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:812:28
```

### Commands

```
     -1:43.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.tinted-tab-bar.compact-tab-bar.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.paint-cursor.theme-monokai.theme-atom-material-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-ctags 5.0.0 
atom-jade 0.3.0 
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
auto-update-packages 1.0.1 
bracket-padder 0.4.1 
busy-signal 1.3.0 
file-icons 2.1.1 
git-plus 7.3.3 
highlight-line 0.12.0 
highlight-selected 0.12.0 
intentions 1.1.2 
language-babel 2.57.0 
language-docker 1.1.7 
language-haml 0.24.1 
linter 2.1.0 
linter-eslint 8.1.4 
linter-rubocop 1.1.1 
linter-ui-default 1.2.1 
monokai 0.22.0 
open-git-modified-files 0.2.4 
pigments 0.39.1 
project-manager 3.3.4 
ruby-block 0.3.6 
script 3.14.1 
sort-lines 0.14.0 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.1 
todo-show 1.11.0 
tree-view-git-status 1.3.1 
zentabs 0.8.8 
```

**Comment by bSushil** [comment]
Problem with atom:
Error: Cannot find module 'mobx'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/sushil/.atom/packages/project-manager/lib/project-manager.js:11:13)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:721:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:173:16)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:779:28

**Comment by Darkbladecr** [comment]
Please use `apm install project-manager` to install the package. If you really need to install it manually you need to run `apm install` to install all the dependencies.
