### ISSUE TITLE
Uncaught TypeError: q.drain is not a function

### ISSUE THREAD

**Issue by ghost** [danielbrodin/atom-project-manager#344]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package 3.3.5

### Stack Trace

Uncaught TypeError: q.drain is not a function

```
At /Users/defabriek/.atom/packages/project-manager/node_modules/async/lib/async.js:909

TypeError: q.drain is not a function
    at /packages/project-manager/node_modules/async/lib/async.js:909:23
    at /packages/project-manager/node_modules/async/lib/async.js:44:16
    at /packages/project-manager/node_modules/fs-plus/lib/fs-plus.js:438:24
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -0:17.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:04.4.0 remote-sync:upload-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.30.3 
atom-clock 0.1.12 
atom-ftp-editor 0.5.0 
atom-terminal-tab 0.2.2 
auto-indent 0.5.0 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.8 
ftp-remote-edit 0.11.7 
intentions 1.1.2 
linter 2.2.0 
linter-jshint 3.1.5 
linter-ui-default 1.6.2 
livereload 0.4.4 
minimap 4.28.2 
minimap-selection 4.4.0 
pigments 0.39.1 
project-manager 3.3.5 
remote-sync 4.1.5 
selection-highlight 0.1.6 
SFTP-deployment 1.0.2 
```

**Comment by TitanNano** [comment]
I'm also getting this error a lot.
