### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/Informatics/Scripts/Carians/echoes/include/...

### ISSUE THREAD

**Issue by Juanses** [danielbrodin/atom-project-manager#359]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package 3.3.5

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir '/Users/juan/Informatics/Scripts/Carians/echoes/include/Medical/css'

```
At /Users/juan/.atom/packages/project-manager/node_modules/mkdirp/index.js:92

Error: EEXIST: file already exists, mkdir '/Users/juan/Informatics/Scripts/Carians/echoes/include/Medical/css'
    at Object.fs.mkdirSync (fs.js:855:18)
    at Function.sync (/packages/project-manager/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/Remote-FTP/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at ConnectorFTP._getFile (/packages/remote-ftp/lib/connectors/ftp.js:200:8)
    at /packages/remote-ftp/lib/connectors/ftp.js:342:14
    at /packages/remote-ftp/lib/connectors/ftp.js:192:7
    at tryApply (/packages/remote-ftp/lib/connectors/ftp.js:12:14)
    at /packages/remote-ftp/lib/connectors/ftp.js:175:7
    at Object.cb (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:526:13)
    at /packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:117:22)
    at emitTwo (events.js:111:20)
    at Parser.emit (events.js:191:7)
    at Parser._write (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/parser.js:61:10)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Parser.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (/packages/Remote-FTP/node_modules/@icetee/ftp/lib/connection.js:290:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -6:25.6.0 remote-ftp:add-file (div.header.list-item)
     -6:24.5.0 core:confirm (input.hidden-input)
     -6:20.4.0 remote-ftp:delete-selected (span.name.icon.icon-file-text)
     -6:14.2.0 remote-ftp:refresh-selected (span.name.icon.icon-file-directory)
     -6:08.8.0 remote-ftp:add-folder (span.name.icon.icon-file-directory)
     -6:08.1.0 core:confirm (input.hidden-input)
     -2:02.9.0 project-find:show (input.hidden-input)
     -2:01.4.0 core:confirm (input.hidden-input)
     -1:11 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -1:06.2.0 core:confirm (input.hidden-input)
     -0:58 remote-ftp:add-file (span.name.icon.icon-file-directory)
     -0:54 core:confirm (input.hidden-input)
     -0:44.1.0 remote-ftp:refresh-selected (div.header.list-item)
     -0:41.5.0 remote-ftp:disconnect (span.name.icon.icon-file-directory)
     -0:19.4.0 tree-view:toggle (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:06.5.0 tree-view:remove (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
busy-signal 1.4.3 
hyperclick 0.1.3 
intentions 1.1.5 
language-mjml 1.10.0 
linter 2.2.0 
linter-ui-default 1.6.4 
modular-snippets 0.1.3 
project-manager 3.3.5 
remote-atom 1.3.11 
remote-edit 1.9.0 
Remote-FTP 1.1.4 
uikit-atom 0.2.2 
```

**Comment by danielbrodin** [comment]
This seems to have to do with the remote ftp package
