### ISSUE TITLE
Uncaught Error: Cannot find module 'season'

### ISSUE THREAD

**Issue by marvinomar** [danielbrodin/atom-project-manager#64]
Uncaught Error: Cannot find module 'season'

**Atom Version**: 0.155.0
**System**: linux 3.14-1-amd64
**Thrown From**: [atom-project-manager-1.14.1](https://github.com/danielbrodin/atom-project-manager) package, v1.14.1

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At module.js:346

Error: Cannot find module 'season'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:380:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.module.exports.addProject (/home/administrador/.atom/packages/atom-project-manager-1.14.1/lib/project-manager.coffee:137:12)
  at ProjectManagerAddView.module.exports.ProjectManagerAddView.confirm (/home/administrador/.atom/packages/atom-project-manager-1.14.1/lib/project-manager-add-view.coffee:37:21)
  at atom-text-editor.<anonymous> (/home/administrador/.atom/packages/atom-project-manager-1.14.1/lib/project-manager-add-view.coffee:1:1)
  at atom-text-editor.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:115:32)
  at atom-text-editor.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-text-editor.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by pdostal** [comment]
Got the same error :crying_cat_face:

**Comment by danielbrodin** [comment]
Have you tried updating atom and project manager to the latest release?

**Comment by pdostal** [comment]
Sorry, I lost this thread and I didn't be able to inform you...:

@danielbrodin yes, I updated Atom, APM and **reinstall this package**.
And after that, it works fine ! :+1:

**Comment by danielbrodin** [comment]
Great :)
