### ISSUE TITLE
Uncaught Error: Cannot find module 'underscore'

### ISSUE THREAD

**Issue by parkerproject** [danielbrodin/atom-project-manager#68]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: Mac OS X 10.10.1
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v1.9.0

### Stack Trace

Uncaught Error: Cannot find module 'underscore'

```
At module.js:346

Error: Cannot find module 'underscore'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Users/hello/.atom/packages/project-manager/node_modules/underscore-plus/lib/underscore-plus.js:5:7)
  at Object.<anonymous> (/Users/hello/.atom/packages/project-manager/node_modules/underscore-plus/lib/underscore-plus.js:499:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Users/hello/.atom/packages/project-manager/node_modules/season/lib/cson.js:8:7)
  at Object.<anonymous> (/Users/hello/.atom/packages/project-manager/node_modules/season/lib/cson.js:307:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.module.exports.loadCurrentProject (/Users/hello/.atom/packages/project-manager/lib/project-manager.coffee:69:12)
  at /Users/hello/.atom/packages/project-manager/lib/project-manager.coffee:23:10
  at Object.cb [as oncomplete] (fs.js:187:19)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.2.4
javascript-snippets, v1.0.0
jslint, v0.10.1
project-manager, v1.9.0
seti-syntax, v0.1.7
seti-ui, v0.3.5

# Dev
No dev packages
```

/cc @atom/core

**Comment by danielbrodin** [comment]
have you updated to the latest version and does it still exist?

**Comment by makmonty** [comment]
I'm having this issue when opening the project list.

[Enter steps to reproduce below:]

1. Open the project list via shortcut or menu.

**Atom Version**: 1.3.0
**System**: Ubuntu 15.10
**Thrown From**: [project-manager](https://github.com/danielbrodin/atom-project-manager) package, v2.7.3


### Stack Trace

Uncaught Error: Cannot find module 'underscore'

```
At module.js:338

Error: Cannot find module 'underscore'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/angel/.atom/packages/project-manager/node_modules/underscore-plus/lib/underscore-plus.js:5:7)
    at Object.<anonymous> (/home/angel/.atom/packages/project-manager/node_modules/underscore-plus/lib/underscore-plus.js:522:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/angel/.atom/packages/project-manager/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:8:9)
    at Object.<anonymous> (/home/angel/.atom/packages/project-manager/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:634:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/angel/.atom/packages/project-manager/node_modules/atom-space-pen-views/lib/main.js:4:10)
    at Object.<anonymous> (/home/angel/.atom/packages/project-manager/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/angel/.atom/packages/project-manager/lib/projects-list-view.js:15:26)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at atom-workspace.projectManagerListProjects (/home/angel/.atom/packages/project-manager/lib/project-manager.js:41:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:00.8.0 project-manager:list-projects (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-beautify",
      "vim-mode",
      "filetype-color",
      "atom-color-highlight",
      "fonts"
    ]
  },
  "project-manager": {}
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
color-picker, v2.0.14
editorconfig, v1.2.4
file-icons, v1.6.14
highlight-selected, v0.11.1
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-csslint, v1.2.0
linter-js-yaml, v1.2.5
linter-jshint, v1.2.2
linter-sass-lint, v0.6.3
minimap, v4.19.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
pigments, v0.19.7
project-manager, v2.7.3

# Dev
No dev packages
```
